## Server Configuration
server:
  port: 8080

spring:
  application:
    name: soup-api
  data:
    jdbc:
      repositories:
        enabled: false
    ## Redis Configuration
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
    ## MongoDB Configuration
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_NAME}.mongodb.net/${MONGODB_DATABASE}?authSource=admin&retryWrites=true&w=majority

  ## Database Configuration
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://${POSTGRESQL_URL}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ## JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


## Springdoc Configuration
springdoc:
  api-docs:
    path: /api/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  group-configs:
    - group: all-api
      paths-to-match:
        - /**
      paths-to-exclude:
        - /favicon.ico
        - /health
    - group: jwt-api
      paths-to-match:
        - /api/**
  #  show-actuator: true


## AWS S3 Configuration
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: soup-bucket
